=== xqinzi/framework/src/resources/etc/resources/auditorResources.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="auditorResources">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="auditor" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="appenders">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="appender">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="options">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="option" maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType>
																		<xs:simpleContent>
																			<xs:extension base="xs:string">
																				<xs:attribute type="xs:string" name="id" use="required"/>
																				<xs:attribute type="xs:string" name="value" use="required"/>
																			</xs:extension>
																		</xs:simpleContent>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="class" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="id" use="required"/>
						<xs:attribute type="xs:string" name="level" use="required"/>
						<xs:attribute type="xs:boolean" name="default" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xqinzi/framework/src/resources/etc/resources/auditorResources.xml
<?xml version="1.0"?>

<auditorResources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:noNamespaceSchemaLocation="auditorResources.xsd">
	<auditor id="default" level="debug" default="true">
		<appenders>
			<appender class="br.com.concepting.framework.audit.appenders.ConsoleAuditorAppender">
				<options>
					<option id="layoutClass" value="br.com.concepting.framework.audit.appenders.AuditorPatternLayout"/>
					<option id="layoutPattern" value="[#{createDate}][#{systemModule}][#{userName}][#{systemSession.ip}/#{systemSession.hostName}][#{entityId} - #{businessId}] #{businessComplement} -> #{statusCode} #{statusMessage}"/>
				</options>
			</appender>
		</appenders>
	</auditor>
	<auditor id="generate.code" level="info">
		<appenders>
			<appender class="br.com.concepting.framework.audit.appenders.ConsoleAuditorAppender">
				<options>
					<option id="layoutClass" value="br.com.concepting.framework.audit.appenders.AuditorPatternLayout"/>
					<option id="layoutPattern" value="[#{createDate}][#{businessId}] #{businessComplement} -> #{statusCode} #{statusMessage}"/>
				</options>
			</appender>
		</appenders>
	</auditor>
</auditorResources>
